# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oleg/Public/Oleg/course_2/ded/akinator/akinator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oleg/Public/Oleg/course_2/ded/akinator/akinator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Public/Oleg/course_2/ded/akinator/akinator/CMakeFiles /home/oleg/Public/Oleg/course_2/ded/akinator/akinator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oleg/Public/Oleg/course_2/ded/akinator/akinator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named akinator

# Build rule for target.
akinator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 akinator
.PHONY : akinator

# fast build rule for target.
akinator/fast:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/build
.PHONY : akinator/fast

#=============================================================================
# Target rules for targets named akinator-tree-print

# Build rule for target.
akinator-tree-print: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 akinator-tree-print
.PHONY : akinator-tree-print

# fast build rule for target.
akinator-tree-print/fast:
	$(MAKE) -f CMakeFiles/akinator-tree-print.dir/build.make CMakeFiles/akinator-tree-print.dir/build
.PHONY : akinator-tree-print/fast

auxilary_functions/my_stack.o: auxilary_functions/my_stack.cpp.o

.PHONY : auxilary_functions/my_stack.o

# target to build an object file
auxilary_functions/my_stack.cpp.o:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/auxilary_functions/my_stack.cpp.o
.PHONY : auxilary_functions/my_stack.cpp.o

auxilary_functions/my_stack.i: auxilary_functions/my_stack.cpp.i

.PHONY : auxilary_functions/my_stack.i

# target to preprocess a source file
auxilary_functions/my_stack.cpp.i:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/auxilary_functions/my_stack.cpp.i
.PHONY : auxilary_functions/my_stack.cpp.i

auxilary_functions/my_stack.s: auxilary_functions/my_stack.cpp.s

.PHONY : auxilary_functions/my_stack.s

# target to generate assembly for a file
auxilary_functions/my_stack.cpp.s:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/auxilary_functions/my_stack.cpp.s
.PHONY : auxilary_functions/my_stack.cpp.s

main_sources/akinator.o: main_sources/akinator.cpp.o

.PHONY : main_sources/akinator.o

# target to build an object file
main_sources/akinator.cpp.o:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/main_sources/akinator.cpp.o
.PHONY : main_sources/akinator.cpp.o

main_sources/akinator.i: main_sources/akinator.cpp.i

.PHONY : main_sources/akinator.i

# target to preprocess a source file
main_sources/akinator.cpp.i:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/main_sources/akinator.cpp.i
.PHONY : main_sources/akinator.cpp.i

main_sources/akinator.s: main_sources/akinator.cpp.s

.PHONY : main_sources/akinator.s

# target to generate assembly for a file
main_sources/akinator.cpp.s:
	$(MAKE) -f CMakeFiles/akinator.dir/build.make CMakeFiles/akinator.dir/main_sources/akinator.cpp.s
.PHONY : main_sources/akinator.cpp.s

main_sources/print_tree.o: main_sources/print_tree.cpp.o

.PHONY : main_sources/print_tree.o

# target to build an object file
main_sources/print_tree.cpp.o:
	$(MAKE) -f CMakeFiles/akinator-tree-print.dir/build.make CMakeFiles/akinator-tree-print.dir/main_sources/print_tree.cpp.o
.PHONY : main_sources/print_tree.cpp.o

main_sources/print_tree.i: main_sources/print_tree.cpp.i

.PHONY : main_sources/print_tree.i

# target to preprocess a source file
main_sources/print_tree.cpp.i:
	$(MAKE) -f CMakeFiles/akinator-tree-print.dir/build.make CMakeFiles/akinator-tree-print.dir/main_sources/print_tree.cpp.i
.PHONY : main_sources/print_tree.cpp.i

main_sources/print_tree.s: main_sources/print_tree.cpp.s

.PHONY : main_sources/print_tree.s

# target to generate assembly for a file
main_sources/print_tree.cpp.s:
	$(MAKE) -f CMakeFiles/akinator-tree-print.dir/build.make CMakeFiles/akinator-tree-print.dir/main_sources/print_tree.cpp.s
.PHONY : main_sources/print_tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... akinator"
	@echo "... akinator-tree-print"
	@echo "... auxilary_functions/my_stack.o"
	@echo "... auxilary_functions/my_stack.i"
	@echo "... auxilary_functions/my_stack.s"
	@echo "... main_sources/akinator.o"
	@echo "... main_sources/akinator.i"
	@echo "... main_sources/akinator.s"
	@echo "... main_sources/print_tree.o"
	@echo "... main_sources/print_tree.i"
	@echo "... main_sources/print_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

